use_frameworks! :linkage => :static
workspace 'Demo.xcworkspace'
install! 'cocoapods'
def common
  pod 'Libass', :path => '../'
  pod 'FFmpegKit', :path => '../'
#  pod 'Libass',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
#  pod 'FFmpegKit',:git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'
end
target 'iOS' do
  project 'Demo.xcodeproj'
  platform :ios, '16.0'
  common
end
target 'macOS' do
  project 'Demo.xcodeproj'
  platform :osx, 10.15
  common
end
target 'tvOS' do
  project 'Demo.xcodeproj'
  platform :tvos, '16.0'
  common
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
