on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build All Platforms
    runs-on: macos-15
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
          xcode-select -p
          xcodebuild -version

      - name: Build iOS
        run: |
          cd Demo
          pod install
          xcodebuild -workspace Demo.xcworkspace -scheme iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' build

      - name: Build macOS
        run: |
          cd Demo
          xcodebuild -workspace Demo.xcworkspace -scheme macOS -sdk macosx -destination 'platform=macOS,arch=arm64' build

      - name: Build tvOS
        run: |
          cd Demo
          xcodebuild -workspace Demo.xcworkspace -scheme tvOS -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' build

      - name: Build visionOS
        run: |
          cd Demo
          xcodebuild -workspace Demo.xcworkspace -scheme visionOS -sdk xrsimulator -destination 'platform=visionOS Simulator,name=Apple Vision Pro' build
